"""add_agile_package

Revision ID: e8d07cc62fd4
Revises: c0acc1e1a1b5
Create Date: 2019-09-25 11:50:37.352115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8d07cc62fd4'
down_revision = 'c0acc1e1a1b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agile_epic',
    sa.Column('deleted', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), server_default='0', nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agile_user_story',
    sa.Column('deleted', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('epic_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), server_default='0', nullable=True),
    sa.ForeignKeyConstraint(['epic_id'], ['agile_epic.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agile_task',
    sa.Column('deleted', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_story_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), server_default='0', nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects_project.id'], ),
    sa.ForeignKeyConstraint(['user_story_id'], ['agile_user_story.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agile_task')
    op.drop_table('agile_user_story')
    op.drop_table('agile_epic')
    # ### end Alembic commands ###
